### ISSUE TITLE
Facebook Requires SSL

### ISSUE THREAD

**Issue by followbl** [lirantal/cypress-social-logins#102]
1.) Thank you for this lib.

2.) Would've totally put this in Github Discussions because there's nothing wrong with this lib at all - more trying to see if anyone has figured this out.

3.) Facebook has recently required SSL for even apps in development mode - which has basically made all of our tests using oAuth not possible. Within our app we have Facebook, Twitter and Linkedin and Twitter and Linkedin have HEAVY checks on auth requests coming from unrecognized IP's. 

fwiw: leveraging `baseLoginConnect` from this lib works PERFECTLY.

Has anyone found a way to use any of the above 3 social providers on a CI with localhost? Thanks in advance anyone reading...

**Comment by lirantal** [comment]
Going to close this for being stale but if any issues remain or more context to be shared, please comment and will re-open.
