### ISSUE TITLE
How to bypass Facebook cookie consent?

### ISSUE THREAD

**Issue by alucardu** [lirantal/cypress-social-logins#104]
cypress-social-logins": "^1.11.3
windows 10
nodejs: v14.2.0

```
describe('Login', () => {
  it('Login through Facebook', () => {
    const loginUrl = 'http://localhost:3000'
    const socialLoginOptions = {
      username: '**',
      password: '**',
      loginUrl,
      headless: false,
      logs: false,
      loginSelector: '[data-cy=login_facebook]'
    }

    return cy.task('FacebookSocialLogin', socialLoginOptions).then(() => {
    })
  })
})
```

![image](https://user-images.githubusercontent.com/779921/124600929-1c4a1600-de1c-11eb-8666-3b13e3db9e0d.png)

**Comment by lirantal** [comment]
Hi there

Looks like you missed up on the disclaimer in the README: 
![image](https://user-images.githubusercontent.com/316371/124496630-58508d00-ddc2-11eb-9e2c-532ceba27194.png)

**Comment by lirantal** [comment]
Specifically, about the cookie consent, you would need to clone the cypress-social-logins source code and add a logic block to detect that dialog and approve so you can continue with the flow.

**Comment by alucardu** [comment]
I didn't miss the disclaimer, it's pretty hard to miss ;)m I'm running the test on my private laptop. Thanks for the tip, so this isn't something that's getting picked up by the dev(s)? I've seen multiple people having the same cookie consent issue.

**Comment by lirantal** [comment]
Got it, yes. So, indeed you'd need to add the cookie popup detection to the code. I don't have any available time soon to do this but I'm happy to receive a pull request and merge if you're up for it.
