### ISSUE TITLE
Cypress Social login failing with redirecting to a new blank page.

### ISSUE THREAD

**Issue by Cardoso-topdev** [lirantal/cypress-social-logins#105]
Hi @lirantal and others!
I am going to test a social login with cypress. I installed this plugin and followed this guides. 
It seems social login success but it redirect to the other new blank page.
I want to do social login with a popup dialog and continue working on my website without redirecting to the other page.
Here is the option object I used.
```
const socialLoginOptions = {
  username,
  password,
  isPopup: true
}
```
And this is the Cypress test screen shot.
![image](https://user-images.githubusercontent.com/75736745/128439803-f4eb0072-f05f-4107-839a-921f64298b09.png)

Please have a look and let me know what I missed or what I am wrong.
Thank you very much.

**Comment by lirantal** [comment]
Going to close this for being stale but if any issues remain or more context to be shared, please comment and will re-open.
