### ISSUE TITLE
After the successful Social login, cookies are set to the browser but the client App that uses Oauth is unable to complete login.

### ISSUE THREAD

**Issue by sarathk-blink** [lirantal/cypress-social-logins#106]
Hello Team,

After a successful google-social-login using the pop-up window, we see that the cookies are being set (visible on the left side of the cypress window that runs automation) but when the code hits on the login button after being redirected to the client App that uses Oauth, the application pretends like cookies were never set and cannot login. 

We would then have to pause cypress run, inspect the page -> Under application -> Cookies -> clear all cookies ( for the ones set by this plugin earlier ), manually hit the login button on our client app and perform social login and only then the cookies are properly set to let our app login.

The issue was first reported on one machine, now we have the same issue while running on others too (not CI machines) and it started showing similar behavior for another application that uses Oauth.

Cypress: 6.9.1
Social Login: ^1.11.2
Cypress Chrome Version: 94.0.4606.8
Platform : OS X Catalina (10.15.7)

Appreciate any help.

**Comment by lirantal** [comment]
Going to close this for being stale but if any issues remain or more context to be shared, please comment and will re-open.
