### ISSUE TITLE
Question About additional steps

### ISSUE THREAD

**Issue by davidkhayutin** [lirantal/cypress-social-logins#111]
- **Library Version**: 1.13.0
- **OS**: Mac
- **Node.js Version**: 16+

Hello

I have been able to successfully login with google - however on my app - after google login completes - there is an additional step to fill out within my application - and I wondering if something like this will be possible to do 

I read the documentation regarding additional steps - but this does not seem to integrate with using the native `GoogleSocialLogin` or perhaps I am using it wrong

If so could you please supply a working example of how that would look in both the config file but also the test case

**Comment by lirantal** [comment]
You can do the in-app step in your own Cypress test code, that shouldn't be part of this plugin.

**Comment by davidkhayutin** [comment]
I dont think it will work that way given how the app is currently build

currently in my extra steps function I am trying to find an element on screen but I get an error every time 

```
const completeRegistrationFlow = async ({ page, options } = {}) => {
  await page.waitForSelector('#schoolSelection')
}
```
![Screen Shot 2022-01-27 at 11 37 53 AM](https://user-images.githubusercontent.com/39314878/151431460-ffc74f59-1809-4d7f-a880-e26e8f01f0bc.png)



being called with 

```
  on('task', {
    customizedLogin: (options) => {
      options.additionalSteps = completeRegistrationFlow
      return CustomizedLogin(options)
    },
  })
  ```

**Comment by lirantal** [comment]
That element is part of the login to Google screen or on your own app?

**Comment by davidkhayutin** [comment]
on the app - but its showing up in chromium - after google pop up closes on successful login

**Comment by lirantal** [comment]
The only callbacks that can help you are `postLoginSelector` to validate the login and `postLoginClick`. When the login is successful, you should do the rest of the flow of your app in your regular Cypress tests.
