### ISSUE TITLE
Question: Pre Login flow 

### ISSUE THREAD

**Issue by yurakhomitsky** [lirantal/cypress-social-logins#116]
Before I get to Microsoft I have to go through some additional flow.

1. I'm visiting my application URL: https://example.com
2. I'm getting redirected to the login screen where I need to press the button
![image](https://user-images.githubusercontent.com/54478076/157699464-5a1ec33a-0122-497d-93fd-b6f0b56e1c7d.png)
3. Next I need to type an email
![image](https://user-images.githubusercontent.com/54478076/157699562-199f1ec0-7c8c-4d05-89b3-474d95270086.png)
4. After that the application navigates to Microsoft and populates my email.
![image](https://user-images.githubusercontent.com/54478076/157699854-9abcba4a-7010-4bf3-bad8-3ee4f054d620.png)

So the question is: Can the options of Microsoft social handle such flow? Can some of the pre-flow be done in cypress and the rest delegated to the puppeteer?

**Comment by wisniewski94** [comment]
Hi @yurakhomitsky , the quick answer is no.

But I have challenged lately similar problem and I have forked the repo and made some changes. You can check the diff between both versions. Luckily the source is not complex.

https://github.com/wisniewski94/cypress-social-logins

We should consider adding some pre-login callback to this repository. My solution is not greatest but solves similar problem
