### ISSUE TITLE
FacebookSocialLogin & GoogleSocialLogin don't work

### ISSUE THREAD

**Issue by enisze** [lirantal/cypress-social-logins#123]
Using the facebook authentication is not working:

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/15271433/168266760-98ee8276-b7a9-4400-915d-8bc993121b45.png">

For google authentication:

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/15271433/168267639-899fe51e-8c62-4486-ae97-411cd4383402.png">

Most of the time also chromium crashes. I am using mac for development.

I saw the outdated package issue, maybe this is something that could solve these issues?

**Comment by muneebrana23** [comment]
@enisze  I'm facing the same issues you reported for both Facebook and Google. were you able to resolve them?

**Comment by waqas973** [comment]
@enisze  I have a same issue with my google account but if you create a new google account with no security in it then it works successfully.
