### ISSUE TITLE
How to handle facebook allow cookies popup which is hardle to process login process/

### ISSUE THREAD

**Issue by muneebrana23** [lirantal/cypress-social-logins#127]
I'm getting below issue  even I'm using 'trackingConsentSelectors' which handles permissions to allow cookie but not working maybe "Allow cookies button is not visible
![image](https://user-images.githubusercontent.com/32091742/195724446-46e52446-8b7d-49fc-8e57-f3026631faa8.png)

**Comment by lirantal** [comment]
Going to close this for being stale but if any issues remain or more context to be shared, please comment and will re-open.
