### ISSUE TITLE
Cypress.Cookies.defaults was removed

### ISSUE THREAD

**Issue by shibukawa** [lirantal/cypress-social-logins#129]
Hi,

README uses the following code snippet, but these API was removed when the latest Cypress v12 was releeased: 

```
        Cypress.Cookies.defaults({
          preserve: cookieName
        })
```

https://github.com/cypress-io/cypress/issues/21472

Official document says, use `cy.session` instead of old APIs. Could you updatge README?

**Comment by shibukawa** [comment]
https://docs.cypress.io/guides/references/migration-guide#Command-Cypress-API-Changes

Migration guide is here:

**Comment by lirantal** [comment]
Thanks for the heads up @shibukawa.
If you want to shoot out a PR that helps solve it and migrate the APIs I'd be happy to merge it.

**Comment by lirantal** [comment]
Going to close this for being stale but if any issues remain or more context to be shared, please comment and will re-open.
