### ISSUE TITLE
Click on social login button does not happen

### ISSUE THREAD

**Issue by bvanderneut** [lirantal/cypress-social-logins#13]
Hello everyone,

I have this object:

```
const socialLoginOptions = {
      username,
      password,
      loginUrl: 'https://www.independer.nl/mijnindepender/inloggen',
      headless: false,
      logs: true,
      loginSelector: 'a[ue="login-met-google"]',
      postLoginSelector: '.account-panel'
    };
```

But what I see it that it opens de chromium browser. Navigates to https://www.independer.nl/mijnindepender/inloggen and then fill in on that page the username. We have the same naming as google does probably. So it does not click or trigger the social login button. Can it be because it's coverd by a cookie law block and it does not trigger it?

Thanks for the help!
Bjorn

**Comment by lirantal** [comment]
hey @bvanderneut 👋

Interesting. So it might just not be able to hit the button because it's not visible due to the cookie banner? Yep, that's probably it.

**Comment by lirantal** [comment]
@bvanderneut I think I have a fix for you with #14

**Comment by bvanderneut** [comment]
@lirantal thanks. I updated my package.json to 

```
"cypress-social-logins": "^1.2.0"
```

Then I did:

```
npm install
```

Restarted Cypress but I am having the same issue. What file/line did you changed? This so I can check if the fix is really in my repro.

Thanks,
Bjorn

**Comment by bvanderneut** [comment]
@lirantal sorry did not check the following link 

https://github.com/lirantal/cypress-social-logins/pull/14/commits/ec9c5a07828e80c1573f9cfe8ab004f047798f39

I now have:

``` 
const socialLoginOptions = {
      username,
      password,
      loginUrl: 'https://www.independer.nl/mijnindepender/inloggen',
      headless: false,
      logs: true,
      preLoginSelector: 'button[type="button"]',
      loginSelector: 'a[ue="login-met-google"]',
      postLoginSelector: '.account-panel'
    };
``` 

And it works!!! Thanks!!

**Comment by lirantal** [comment]
@bvanderneut yay, happy to hear 🤗
