### ISSUE TITLE
Feat: migrate from CircleCI to GitHub Actions

### ISSUE THREAD

**Issue by lirantal** [lirantal/cypress-social-logins#130]
**Is your feature request related to a problem? Please describe.**
Currently this project's CI is maintained with CircleCI

**Describe the solution you'd like**
Remove the CircleCI job setup and create a new GitHub Actions setup

**Comment by Pavan-Nambi** [comment]
hey can i try this ? 😅 @lirantal

**Comment by lirantal** [comment]
Yes :-)

**Comment by lirantal** [comment]
@Pavan-Nambi you can use this as a base: https://github.com/lirantal/snyk-or-snick/blob/master/.github/workflows/main.yml
