### ISSUE TITLE
cy.task('GoogleSocialLogin') is failing

### ISSUE THREAD

**Issue by mcmclarry** [lirantal/cypress-social-logins#137]
- **Library Version**:
- **OS**:
- **Node.js Version**:

**Error:**
![image](https://github.com/lirantal/cypress-social-logins/assets/56150063/5219fc28-264e-44b7-8c1a-9e7de148128a)

I am trying to use this cypress-social-logins plugin for automating the webpage being tested, having a Google Sign in option. Here are my files:

cypress/plugins/index.js
![image](https://github.com/lirantal/cypress-social-logins/assets/56150063/9f1e87e4-0509-4235-a7c9-6527c2a02558)

function (from cypress page) that will be called in actual testing (e2e test file)
![image](https://github.com/lirantal/cypress-social-logins/assets/56150063/35cf8ba8-1f46-4e80-87ee-6b3fa6793925)

I have followed what were written in the read me or guide. Not sure why I am having this error. Would appreciate the help for the possible solution or fix for this issue. Thank you!

I am using latest cypress version (v12.12)
Node: v16.14.0
OS: Windows 10

**Comment by mcmclarry** [comment]
@lirantal Hi, just want to check if you had encountered this issue before? Thanks!

**Comment by BahaaalHalabi01** [comment]
@mcmclarry can you please show the `cypress.config` file ? you should define the task there not in the plugins folder, below is an example of a config file with the google social login
```
 e2e: {
    supportFile: false,
    baseUrl: 'http://localhost:5173',
    setupNodeEvents(on, config) {
      on('task',{
        GoogleSocialLogin:plugins.GoogleSocialLogin
      })
    },
  },
```

**Comment by lirantal** [comment]
Going to close this for being stale but if any issues remain or more context to be shared, please comment and will re-open.
