### ISSUE TITLE
specific puppeteer version is deprecated when installing cypress social logins

### ISSUE THREAD

**Issue by maleozaf** [lirantal/cypress-social-logins#138]

**Comment by maleozaf** [comment]
![Capture](https://github.com/lirantal/cypress-social-logins/assets/81597111/014b1cdf-7089-4cea-ade8-004173bc6c76)

  i got this error when installing cypress social logins, specific puppeteer version is deprecated

**Comment by lirantal** [comment]
Makes sense... we haven't updated the dependencies for this project for a long time.

**Comment by maleozaf** [comment]
> Makes sense... we haven't updated the dependencies for this project for a long time.

let me know when youre done :)

**Comment by lirantal** [comment]
@maleozaf new version released with latest puppeteer: https://www.npmjs.com/package/cypress-social-logins
