### ISSUE TITLE
Any reason you didn't use ES6 import syntax in plugins/index.js? I think that's a Cypress limitation but just want to confirm

### ISSUE THREAD

**Issue by xucao-nvta** [lirantal/cypress-social-logins#28]
First of all great implementation for the Google SSO workaround @lirantal !!!
This is a more question than issue or feature request:
when you required this plugin inside plugins/index.js did you purposely not use the ES6 import syntax before of the Cypress' limitation?
```
const {GoogleSocialLogin} = require('cypress-social-logins').plugins

module.exports = (on, config) => {
  on('task', {
    GoogleSocialLogin: GoogleSocialLogin
  })
}
```
now I tried to convert the `const {GoogleSocialLogin} = require('cypress-social-logins').plugins` to ES6 like this `import { GoogleSocialLogin } from 'cypress-social-logins';` but Cypress GUI runner threw error like this:
```
An unexpected error occurred
The plugins file is missing or invalid.
Your pluginsFile is set to /.../web/test/cypress/plugins/index.js, but either the file is missing, it contains a syntax error, or threw an error when required. The pluginsFile must be a .js or .coffee file.
Please fix this, or set pluginsFile to false if a plugins file is not necessary for your project.
```
Did you run into this issue when you were implementing this plugin?

**Comment by lirantal** [comment]
I actually don't remember if I even tried to use ES6 style here, most probably didn't even try since I'm coming from a Node.js and commonjs type of module system as a background.

Is there a reason you'd like to convert it to ES in particular?

**Comment by xucao-nvta** [comment]
Thank you Liran for your reply!  

No particular reason that I wanted to convert to ES6 but for consistency with the rest of the code.  It turns out this might be a Cypress bug cause it accepts ES6 syntax in other folder integration/, support/, etc.  JS world has moved on to ES6 so I think we need to move along with it. Besides I personally don't like to mix different syntax from different versions. That just looks confusing to me.  Once again thank you for this great SSO plugin and I might come back contribute when I get a chance. 

By the way we have to turn off the headless mode in order to guarantee this plugin would work.  I read from other issues/posts here:[https://github.com/lirantal/cypress-social-logins/issues/15](https://github.com/lirantal/cypress-social-logins/issues/15).  So I went ahead and did some investigation but couldn't console log the google login html page content using page.content() puppeteer function in the headless mode to see what the email input element looks like.  Might circle back on that in the future.  Here are the 2 posts I found from puppeteer: [https://github.com/puppeteer/puppeteer/issues/331](https://github.com/puppeteer/puppeteer/issues/331) and [https://github.com/puppeteer/puppeteer/issues/2913](https://github.com/puppeteer/puppeteer/issues/2913)
You can search 'page.content' on the page

Thanks again for your great work!

**Comment by lirantal** [comment]
Totally agree on mixing up ESM and CJS - that's definitely not a recommended practice. 

On headless mode - we did end up pushing a fix for it (you can see the linked PR in that issue) so if you're still experiencing issues on that let me know.

Otherwise closing the thread. Thanks for the kind words! ❤️
