### ISSUE TITLE
Any posibility to get localStorage 

### ISSUE THREAD

**Issue by alexpirogovqa** [lirantal/cypress-social-logins#29]
Hello. Are there any possibility to get localStorage after login ?

**Comment by lirantal** [comment]
I think that should still be available for you from within Cypress if it's in the same DOM. Isn't it?

**Comment by 24601** [comment]
@lirantal I think @alexpirogovqa is trying to get the localStorage of the puppeteer window as some auth schemes set data in there (scary if it’s sensitive data, yeah, and NOT a secure or best practice, IMO) or sessionStorage (better, I guess, but still not secure or a best practice - although we do sometimes store things like user ids, state data, etc in sessionStorage some times during the auth process that the app expects to be there after a successful auth which would be good to have). 

I have a fork that provides these as ssd and lsd vars alongside the cookie. I’ll submit a PR. @alexpirogovqa - see my GitHub fork in the mean time.
