### ISSUE TITLE
Email is entered in application email button due to absez

### ISSUE THREAD

**Issue by yusufJinadu** [lirantal/cypress-social-logins#30]
Please describe the problem you are trying to solve.
My page has an email input, with 'input[type="email"]'. Immediately the sign in button is clicked, the plugin does not wait till the browser redirects rather, it starts entering the the email on my page's email field

**Describe the solution you'd like**
Email is typed only when clicking on login selector has completely redirected
Please describe the desired behavior.

**Describe alternatives you've considered**
An option to add a delay before entering the email, so that the page redirects before email is typed
Please describe alternative solutions or features you have considered.

**Comment by lirantal** [comment]
I'm not sure what is the issue. Can you describe or show a video of what happens? Why do you need that delay? This plugin waits for cookies to be available and then uses them to apply to Cypress.

Anyway, we do have delay support added, check the README for `loginSelectorDelay`

**Comment by mpoehler** [comment]
I have just seen the problem for myself. In typeUsername() the username is written into the email field of the application, if on the page with the login buttons there is also an input from type email.

Video: https://drive.google.com/file/d/16uyiXG-WpPTO4VlqwjU8j5WgXSxxkVrv/view?usp=sharing

I think I already have a solution for this... probably it is enough to make the selector a bit more precise

**Comment by lirantal** [comment]
Ahh the video makes a lot of sense, thanks for that! :-)
Let's discuss further on the PR
