### ISSUE TITLE
Plugin does not wait for redirection to google to be complete before entering email

### ISSUE THREAD

**Issue by yusufJinadu** [lirantal/cypress-social-logins#31]
My page has an email input, with 'input[type="email"]'. Immediately the sign in button is clicked, the plugin does not wait till the browser redirects rather, it starts entering the the email on my page's email field

Email is typed only when clicking on login selector has completely redirected
Please describe the desired behavior.

An option to add a delay before entering the email, so that the page redirects before email is typed
Please describe alternative solutions or features you have considered.

**Comment by lirantal** [comment]
looks like a dup
