### ISSUE TITLE
Runnning the plugin on a linux machine gives me an error

### ISSUE THREAD

**Issue by shivasrini** [lirantal/cypress-social-logins#32]
First up, big thanks for this awesome plugin. It definitely opens up a lot of options for me with Cypress. I am currently using bitbucket pipelines to run my tests and when I tried to run my test that uses the plugin with Bitbucket I am getting the error below. Any ideas on how to fix or workaround this would be much appreciated. 

> Error: Failed to launch the browser process!
[768:768:0423/165641.025850:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

**Comment by shivasrini** [comment]
Turns out I wasnt passing in the --no-sanbox args to the plugin. Things started to happen afterwards

**Comment by lirantal** [comment]
Ok great, I'll update a FAQ page with that
