### ISSUE TITLE
TimeoutError: waiting for selector "input[type="password"]" failed: timeout 30000ms exceeded

### ISSUE THREAD

**Issue by jjainarpit** [lirantal/cypress-social-logins#34]

**Comment by jjainarpit** [comment]
I figured it out! Thanks.

**Comment by lirantal** [comment]
@jjainarpit thanks for chiming in!
any chance you want to share with us what was the issue? would be helpful for the next person who gets into trouble :-)

**Comment by jjainarpit** [comment]
Sure why not! it has to do with plugin installation. So, the issue was occurring when I did install cypress first and then a social plugin. However, when I just did install just social plugin it worked. I am not sure what really happened but it got fixed.  Also, something with headless = true. When I did headless = false, everything worked like charm

**Comment by lirantal** [comment]
Not sure why that would be an issue. I mean, obviously you need cypress too...?
Thanks for sharing.

**Comment by surykumar** [comment]
Hi, I am trying to test the google sign in & using this package. There are couples of issues am facing.
- Whenever I run the test, I am not seeing it running in any window, as in the attached screenshot you can see that the loginSelector is clicked & it's showing error in finding email input, which means the loginSelector is available. why am I not seeing it in the cypress default runner page? also if I make headless = false, I see a new browser tab opened.

![Screenshot from 2020-10-07 14-24-32](https://user-images.githubusercontent.com/31002063/95311107-ce16df00-08aa-11eb-939f-fa286edb3f6c.png)
![Screenshot from 2020-10-07 14-25-28](https://user-images.githubusercontent.com/31002063/95311115-cf480c00-08aa-11eb-8b9b-5b036d690280.png)
![Screenshot from 2020-10-07 14-27-04](https://user-images.githubusercontent.com/31002063/95311119-d0793900-08aa-11eb-94a3-08af7ca34892.png)
