### ISSUE TITLE
getAllBrowserCookies returning undefined

### ISSUE THREAD

**Issue by jjainarpit** [lirantal/cypress-social-logins#36]

**Comment by lirantal** [comment]
Is it possible there are no cookies set on the page?

**Comment by wadehammes** [comment]
Im also having this issue but I have made sure that there is a cookie in localStorage that matches the cookie needed for `cookieName`.

**Comment by lirantal** [comment]
@wadehammes cookies are returned from... a cookie, not localStorage :-)
however, this last PR #38 had indeed introduced an ability to capture that from the localStorage and from sessionStorage. You'd need to explicitly set that as the cookie for Cypress.
