### ISSUE TITLE
TimeoutError: waiting for selector "#signIn" failed: timeout 30000ms exceeded

### ISSUE THREAD

**Issue by eledwinn** [lirantal/cypress-social-logins#41]
I am getting this error only when I use `headless: true` in the config. I downloaded this repo and debugged the problem locally, and what happens is that the Login button has a different id.

I took a screenshot and wrote the HTML of the login page when the exception occurred.

![screenshot](https://user-images.githubusercontent.com/2124740/84189980-c3168400-aa5b-11ea-87d8-443e2fa94926.png)

Part of popup page html code
```
...
<div jscontroller="VfPfjf" jsname="vZSTIf">
  <label class="XJ6xof" for="password">Introduce tu contraseña</label>
  <input id="password" name="Passwd" type="password" spellcheck="false" autofocus="" class="mCAa0e" jsname="pRFXed" />
</div>
<input type="submit" class="MK9CEd MVpUfe" jsname="M2UYVd" jscontroller="rrJN5c" jsaction="aJAbCd:zbvklb" value="Iniciar sesión" id="submit" />
...
```
The Login button has a `#submit` as id, but the plugin search `#signIn`.
https://github.com/lirantal/cypress-social-logins/blob/db256bc78d1f52a47bb979b6f8ed2b87c7e94563/src/Plugins.js#L114

My configuration:
```
const socialLoginOptions = {
  username,
  password,
  loginUrl,
  headless: true,
  logs: false,
  getAllBrowserCookies: true,
  loginSelector: 'button[id="googleBtn"]',
  postLoginSelector: '.photo-profile',
  loginSelectorDelay: 500,
  popupDelay: 1000,
  isPopup: true
}
```

Suggestion
Change selector by first `input[type='submit]` coincidence, works for me.

**Comment by lirantal** [comment]
Thanks @eledwinn for the bug report.
Do you want to send a PR that fixes it? it could check if a buttonSelector of "#signIn" exists, and if not, try the "#submit" selector.

**Comment by eledwinn** [comment]
Yes, I will be sending a PR this week!

**Comment by lirantal** [comment]
That would be awesome 😍
