### ISSUE TITLE
"Couldn't sign you in" This browser or app may not be secured, Google login fails

### ISSUE THREAD

**Issue by mumairofficial** [lirantal/cypress-social-logins#43]
Hello,

I am trying to perform Google Auth operation and using the same example code provided in README file.

Initially with option `headless: true` it took long and returns following error:

![image](https://user-images.githubusercontent.com/6498132/84844900-e39a9b80-b064-11ea-91de-047e02cb9498.png)

Then I tried to debug the situation and toggled `headless: false` then situation was different.

![image](https://user-images.githubusercontent.com/6498132/84845050-32e0cc00-b065-11ea-8dd5-1e9ca43df8ef.png)

I have recorded small video of this: https://www.loom.com/share/0b13b447f9c54a4e81beeee856e45544

Setup code:
```js
it('Login through Google', () => {
    const username = Cypress.env('LOGIN_EMAIL');
    const password = Cypress.env('PASSWORD');
    const loginUrl = Cypress.env('LOGIN_URL');
    const cookieName = Cypress.env('COOKIE_NAME');
    const socialLoginOptions = {
      username,
      password,
      loginUrl,
      headless: true, // for debugging I used false option 
      isPopup: true,
      logs: false,
      loginSelector: 'button',
      popupDelay: 3000,
    };

    return cy.task('GoogleSocialLogin', socialLoginOptions).then(({ cookies }) => {
      cy.clearCookies();

      const cookie = cookies.filter((cookie) => cookie.name === cookieName).pop();
      if (cookie) {
        cy.setCookie(cookie.name, cookie.value, {
          domain: cookie.domain,
          expiry: cookie.expires,
          httpOnly: cookie.httpOnly,
          path: cookie.path,
          secure: cookie.secure,
        });

        Cypress.Cookies.defaults({
          whitelist: cookieName,
        });
      }
    });
  });
```

```js
{
  "chromeWebSecurity": true // I have tried all 3 options (removing this property, true and false
}
```

Not sure if I am doing something wrong or it requires extra configurations. Kindly help!

**Comment by TomaszWaszczyk** [comment]
```
    const username = Cypress.env('LOGIN_EMAIL');
    const password = Cypress.env('PASSWORD');
    const loginUrl = Cypress.env('LOGIN_URL');
    const cookieName = Cypress.env('COOKIE_NAME');
```

Do you provide real Google credentials? And what is the `LOGIN_URL` and `COOKIE_NAME` for you?

**Comment by mumairofficial** [comment]
Yes I provided real Google credentials and here is my `cypress.env.json`
```json
{
  "LOGIN_EMAIL": "<valid gmail address>",
  "PASSWORD": "<password>",
  "LOGIN_URL": "http://localhost:4200/login",
  "COOKIE_NAME": "g_authed_cookie"
}
```
Is that a problem?

**Comment by TomaszWaszczyk** [comment]
Have you had maybe such kind of issue: https://stackoverflow.com/questions/62437026/property-cookies-does-not-exist-on-type-undefined ?

**Comment by mumairofficial** [comment]
Probably true, plugin documentation didn't explain much on that.

**Comment by lirantal** [comment]
Hey @mumairofficial,

That issue seems to be more related to Google and their security constraints than to the plugin itself. That's a message coming in from Google's own platform once you try to login.

Apparently, other people have reported something similar with selenium and probably other tools too? See here: https://stackoverflow.com/questions/59380356/how-to-handle-browser-or-app-may-not-be-secure-issue-with-web-driver-selenium-py

There's also an official question on this on Google's support: https://support.google.com/accounts/thread/22873505?hl=en

**Comment by chan-dev** [comment]
@lirantal so there's no way to test login with gmail with cypress as of the moment?

**Comment by lirantal** [comment]
@chan-dev sure there is and last I checked in my E2E tests it works fine. The issue described above is something related to gmail and the account the user tried to sign-up with, not to Cypress or to this plugin.

**Comment by chan-dev** [comment]
@lirantal if you don't mind, can you show a snippet of yours for gmail login? i've been struggling to make mine work. I haven't tried this cypress plugin yet but i've seen this issue so i'm having thoughts.

**Comment by lirantal** [comment]
Yes, see the code here that adds an example E2E test: https://github.com/lirantal/cypress-social-logins/pull/20
It currently fails but due to a CI configuration rather than an actual problem with the plugin.

**Comment by chan-dev** [comment]
Thanks, i've looked at the code. I've got a couple of questions. 
1. First, do i have to set the userAgent in cypress json for it to work
2. Is there a difference between String.fromCharCode and the constant string 'Enter' on keyboard press?

**Comment by lirantal** [comment]
1. IIRC that was something default I took from the Cypress setup. It shouldn't matter unless Google social auth is doing something around it, but not to my knowledge or experience.
2. I don't know, worth checking with the pupetteer docs too I assume.

**Comment by lirantal** [comment]
Closing this one as I don't see this being a bug in the plugin or in Cypress.
Happy to re-open if anybody wants to contribute more information here.

**Comment by denysvitali** [comment]
Just remove the `--enable-automation` flag from Chrome / Chromium:

```js
module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
      on('before:browser:launch', (browser, launchOptions) => {
        console.log(launchOptions.args);
        let removeFlags = [
          '--enable-automation',
        ];
        launchOptions.args = launchOptions.args.filter(value => !removeFlags.includes(value));
        return launchOptions
      })
    },
  },
});
```

and enjoy:

![image](https://github.com/lirantal/cypress-social-logins/assets/4939519/06769faf-f30a-48f5-b4c5-ce999d5f79ff)

**Comment by lirantal** [comment]
Folks, I'm monitoring but not actively maintaining the project.
If anyone wants to send a PR or actively join to collaborate on maintaining the project I am happy to facilitate.

Appreciate you folks sharing knowledge and helping here ❤️

**Comment by adnanerlansyah403** [comment]
> Just remove the `--enable-automation` flag from Chrome / Chromium:
> 
> ```js
> module.exports = defineConfig({
>   e2e: {
>     setupNodeEvents(on, config) {
>       // implement node event listeners here
>       on('before:browser:launch', (browser, launchOptions) => {
>         console.log(launchOptions.args);
>         let removeFlags = [
>           '--enable-automation',
>         ];
>         launchOptions.args = launchOptions.args.filter(value => !removeFlags.includes(value));
>         return launchOptions
>       })
>     },
>   },
> });
> ```
> 
> and enjoy:
> 
> ![image](https://private-user-images.githubusercontent.com/4939519/296448416-06769faf-f30a-48f5-b4c5-ce999d5f79ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NTM3ODEsIm5iZiI6MTcxMzg1MzQ4MSwicGF0aCI6Ii80OTM5NTE5LzI5NjQ0ODQxNi0wNjc2OWZhZi1mMzBhLTQ4ZjUtYjRjNS1jZTk5OWQ1Zjc5ZmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjNUMDYyNDQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDdmZDVhMjhiMjQ4Njk5MDY2YmZjOGU0YjA3OTIyYzZiYjU5MjY1ZmE0ZmU2MzQ2MDNhNWE4ZjI5YTBiZWY4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dUvL7mt6gpmge-XmHEN4ZJgR4gb06723VXlEMGluoQY)

This is working for me but only on my local and it doesn't work while running it on the CI/CD github actions
![image](https://github.com/lirantal/cypress-social-logins/assets/88386921/a6868ac2-321b-4c4f-9978-a026bae36571)

**Comment by Jailani134** [comment]
it is working only in headed mode and not working in headless mode can some one provide solution for this?
