### ISSUE TITLE
Property 'cookies' does not exist on type 'undefined'.

### ISSUE THREAD

**Issue by TomaszWaszczyk** [lirantal/cypress-social-logins#44]
I am using TypeScript, installed the plugin, configured `GoogleSocialLogin` plugin and got:

![image](https://user-images.githubusercontent.com/1605705/84933865-cef6eb80-b0d6-11ea-869b-6ba07ffcdbdb.png)

Any idea what I should do?

**Comment by lirantal** [comment]
Assuming this isn't a specific TS issue like a type definition missing - is it possible that no cookies are available after you login? How about you run it in non headless mode so you can see puppetteer and the whole login process to validate if the login is indeed successful and try to check if cookies are at all available?

**Comment by lirantal** [comment]
@TomaszWaszczyk anything new on this one?

**Comment by lirantal** [comment]
Closing due to stale issue.

**Comment by abhiskkk-mp** [comment]
Were we able to login to the app using the social plugin?
If yes, can somebody provide with a working copy of it here
