### ISSUE TITLE
Captcha when running on CI

### ISSUE THREAD

**Issue by tomdohnal** [lirantal/cypress-social-logins#47]
Hi there,

your library works just fine on my own machine. 

However, when running on the CI, Google asks "me" to enter the captcha code after "I" enter the email. 

I know that your library is not possible to control that or bypass it but I wonder if you've encountered that yourself and how did you go about it. (If, e. g., it's somehow possible to disable in somewhere in the Google Developer Console or something similar.)

Feel free to close the issue if you don't have any ideas :) I know that this issue is not really actionable and a little bit off-topic.

Thanks!

**Comment by lirantal** [comment]
Hey there Tom, I noted the same here trying to get the e2e tests passing on CI but facing the same problem: https://github.com/lirantal/cypress-social-logins/pull/20#issuecomment-653673273

I do wonder if we'll have the same issue with other social based logins, but with Google employing their detection of different UA, different IP locations and other stats that introduce a "verify me" and captcha type of verifications I'm not sure we have good ways to respond to that with this plugin.

I'm happy to discuss if you have ideas on what we should try.

**Comment by wadehammes** [comment]
Ive ran into this once, when I moved into a new apartment last weekend. It asked me to verify my phone number after the password submission step (which is one we could potentially fix I believe with some conditional checks).

**Comment by lirantal** [comment]
How would you fix it?

**Comment by wadehammes** [comment]
Im not sure, it relies on a phone number and then the code that gets SMS'd, not sure it's possible.

**Comment by tomdohnal** [comment]
I'm not sure either. The ideal solution would be if Google allowed some sort of "testing accounts" for that purpose. 

I don't think it's really feasible to bypass their security measures in a reliable way. And if Google notices suspicious activity (e. g. logging in X times every day) it may ban the account. Regular Google accounts aren't meant for automatic testing I'm afraid so I don't think there's much we can do about it...

**Comment by lirantal** [comment]
How about if we attempt the use of backup codes to login to the account?

**Comment by tomdohnal** [comment]
I believe that the backup codes are just for one-time usage each. And I don't think there's a programmatic way to generate them.

**Comment by lirantal** [comment]
Yes but I'm thinking that once you use one of them, then Google will allow that UserAgent/IP source and so you'd probably have to just do it once or twice and not use them for each test.

**Comment by tomdohnal** [comment]
It sounds like a feasible workaround as long as Google asks you to fill out an SMS code they sent you. This wasn't my case though. It asked "me" to fill out the captcha code when running on the CI.

![screenshot4](https://user-images.githubusercontent.com/22922179/87520519-5a867c80-c683-11ea-83c1-6b44af9f6b70.png)

**Comment by lirantal** [comment]
In that case it would be hard, I agree. I wouldn't even try to bypass captcha like that.

**Comment by tomdohnal** [comment]
Yes :(
Well, I don't think that there's a general solution for this issue :( I think it can be closed...

But thanks a lot for discussing it with me!
