### ISSUE TITLE
Attach to popup generated by application rather than spawning new window

### ISSUE THREAD

**Issue by symon-skelly** [lirantal/cypress-social-logins#50]
My application under test displays a popup with the Google sign-in dialog upon clicking a button inside a nested iframe, It would be great if we could use this plugin on the popup that is actually populated by the application, or have support for the loginSelector var to accommodate buttons inside iframes.

**Comment by lirantal** [comment]
Seems like you'd need to accommodate for the loginSelector to be clickable within the iframe? also that would be something that won't happen from Cypress as it doesn't have access to the iframe, but rather you'd need to do this with puppeteer

**Comment by lirantal** [comment]
Closing due to stale issue.
