### ISSUE TITLE
waiting for selector "input#identifierId[type="email"]" failed: timeout 30000ms exceeded

### ISSUE THREAD

**Issue by surykumar** [lirantal/cypress-social-logins#57]
Hi, I am trying to test the google sign in & using this package. The issue I am facing is.
- Whenever I run the test, I am not seeing it running in any window, as in the attached screenshot you can see that the loginSelector is clicked & it's showing error in finding email input, which means the loginSelector is available. why am I not seeing it in the cypress default runner page? & having the issue " waiting for selector "input#identifierId[type="email"]" failed". also if I make headless = false, I see a new browser tab opened with the loginSelector Button, am expecting this is not triggering because of the default popups are blocked in chromium. But again if that the case, I am just seeing the login button & the error I get is still the same "waiting for selector "input#identifierId[type="email"]" failed: timeout 30000ms exceeded". 

![Screenshot from 2020-10-07 14-24-32](https://user-images.githubusercontent.com/31002063/95311107-ce16df00-08aa-11eb-939f-fa286edb3f6c.png)
![Screenshot from 2020-10-07 14-25-28](https://user-images.githubusercontent.com/31002063/95311115-cf480c00-08aa-11eb-8b9b-5b036d690280.png)
![Screenshot from 2020-10-07 14-27-04](https://user-images.githubusercontent.com/31002063/95311119-d0793900-08aa-11eb-94a3-08af7ca34892.png)

_Originally posted by @suryakant-kumar in https://github.com/lirantal/cypress-social-logins/issues/34#issuecomment-704803701_

**Comment by lirantal** [comment]
The fact that you don't see anything on Cypress, or a new browser, is because the work for doing the actual login is done using pupetteer. I suggest going through the examples on the README and a branch we have as a reference.

**Comment by ashishnarmen** [comment]
I have run into the same issue.  I added the options `isPopup: true`, `popupDelay: 5000` and `logs: true`.

```
cy.task('GoogleSocialLogin') failed with the following error:
> waiting for selector "input#identifierId[type="email"]" failed: timeout 30000ms exceeded
 at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:159509:20)
From previous event:
    at Context.task (http://localhost:3000/__cypress/runner/cypress_runner.js:159491:16)
From Your Spec Code:
    at Context.eval (webpack:///cypress/integration/social.spec.js:20:17)
From Node.js Internals:
    TimeoutError: waiting for selector "input#identifierId[type="email"]" failed: timeout 30000ms exceeded
      at new WaitTask (project_directory/node_modules/cypress-social-logins/node_modules/puppeteer/lib/DOMWorld.js:549:29)
      at DOMWorld._waitForSelectorOrXPath (project_directory/node_modules/cypress-social-logins/node_modules/puppeteer/lib/DOMWorld.js:478:23)
      at DOMWorld.waitForSelector (project_directory/node_modules/cypress-social-logins/node_modules/puppeteer/lib/DOMWorld.js:432:18)
      at Frame.waitForSelector (project_directory/node_modules/cypress-social-logins/node_modules/puppeteer/lib/FrameManager.js:627:48)
      at Frame.<anonymous> (project_directory/node_modules/cypress-social-logins/node_modules/puppeteer/lib/helper.js:112:24)
      at Page.waitForSelector (project_directory/node_modules/cypress-social-logins/node_modules/puppeteer/lib/Page.js:1122:30)
      at typeUsername (project_directory/node_modules/cypress-social-logins/src/Plugins.js:213:17)
      at baseLoginConnect (project_directory/node_modules/cypress-social-logins/src/Plugins.js:179:10)
      at processTicksAndRejections (internal/process/task_queues.js:94:6)
```

I attempted to setup Fiddler to view the requests and the responses but I wasn't able to analyze and make sense of the HTTP requests. 
```
GET https://apis.google.com/js/api.js HTTP/1.1
GET https://apis.google.com/_/scs/apps-static/_/js/k=oz.........
GET https://accounts.google.com/o/oauth2/iframe
GET https://ssl.gstatic.com/accounts/o/1209952130-idpiframe.js
GET https://accounts.google.com/o/oauth2/iframerpc?action=checkOrigin&origin=http%3A%2F%2Flocalhost%3A3000&c....
```
My local configuration is 
Node: v12.18.4
Mac OS Catalina 10.15.7
In package.json, the dependencies are 

  "devDependencies": {
    "cypress": "^5.3.0",
    "cypress-social-logins": "^1.5.2",
    "puppeteer": "5.3.1",
    "ws": "7.3.1"
  }

Where are the logs being written? I think that might provide me some information on what might be failing.

**Comment by surykumar** [comment]
Also, what I have noticed is, after clicking the login button, it's searching for the email input field. But it's possible to have another account selector login screen (attached 2nd screen) & if that's the case it's unable to find the email input & throwing the error. I am not sure but it might be the reason for this error.

![Screenshot from 2020-10-08 00-43-21](https://user-images.githubusercontent.com/31002063/95377278-f846bc00-08ff-11eb-87bf-84ba062eaa5c.png)
![Screenshot from 2020-10-08 00-43-32](https://user-images.githubusercontent.com/31002063/95377280-f977e900-08ff-11eb-8eb3-cf14b3df7549.png)
![Screenshot from 2020-10-08 00-43-44](https://user-images.githubusercontent.com/31002063/95377282-fa107f80-08ff-11eb-9a5d-bb4a66cbeab0.png)

**Comment by SaveYourTime** [comment]
<img width="1473" alt="截圖 2020-11-19 下午11 43 49" src="https://user-images.githubusercontent.com/35715664/99689829-687d5b80-2ac2-11eb-887b-f983e517e448.png">

> CypressError
cy.task('GoogleSocialLogin') failed with the following error:
> waiting for selector "input#identifierId[type="email"]" failed: timeout 30000ms exceeded
 
For anyone who is facing the same issue and your google auth displayed like a popup, try the `socialLoginOptions` below.
The key point is to set `popupDelay` for more than 3000 milliseconds.

```
const socialLoginOptions = {
      username,
      password,
      loginUrl,
      preLoginSelector: '[data-testid="auth"]',
      loginSelector: 'button[data-provider-id="google.com"]',
      postLoginSelector: '[data-testid="chatroom"]',
      isPopup: true,
      popupDelay: 3000, // <--- this is important !!!
};
```

**Comment by lirantal** [comment]
@SaveYourTime thanks for taking the effort document this for other readers.
Would you be able to open a pull request to the README and add this note on the troubleshooting section in the bottom? 🙏

**Comment by mdn021** [comment]
I'm having this issue as well. I was able to get a screenshot of the page and it looks like I'm getting a more outdated google log in page. Any ideas why this would be?
![google-sign-in](https://user-images.githubusercontent.com/16750455/100035954-15522400-2db4-11eb-89b9-3f179bfa9570.png)

**Comment by lirantal** [comment]
Can you check the selectors on that login page to see if they match what the library is trying to find?

**Comment by mdn021** [comment]
It doesn't. This is html for the email field.

`<input id="Email" type="email" value="" spellcheck="false" name="Email" placeholder="Email or phone" autofocus="">`

**Comment by lirantal** [comment]
@mdn021 we just added a capability for a custom login if you need to adjust the selectors and such. Check the updated README for these options and an example walk through. Goodluck!

**Comment by abhick09** [comment]
Maybe adding a popupDelay: 3000, fixed it for me when i had the same problem in social login options.

**Comment by Kajal-Rani** [comment]
@suryakant-kumar Were you able to fix this issue? I am also facing the same issue.
