### ISSUE TITLE
Support hidden login links

### ISSUE THREAD

**Issue by mullens** [lirantal/cypress-social-logins#6]
Since this plugin doesn't support pop-ups, and our login button uses a pop-up, we added a hidden login button that uses a redirect to make testing work. But since that button was hidden (positioned absolutely off the page), puppeteer's click function failed (since it wants to scroll
the hidden login link into view, and fails when it can't). I couldn't find an easy way to make users
not see the button, but let puppeteer see it.

I was able get around this by forking the plugin and changing the login function's page.click to:
await page.$eval(options.loginSelector, e => e.click())

Is there a better approach here that I could use?

**Comment by lirantal** [comment]
@mullens did you see discussion on https://github.com/lirantal/cypress-social-logins/issues/4 it is somewhat related.

How about clicking it by an id assigned to the button element. Would that work for puppeteer?

**Comment by lirantal** [comment]
@mullens can you see if this PR that landed recently will help you with this? https://github.com/lirantal/cypress-social-logins/pull/14

Closing for now but I'm happy to re-open if needed.
