### ISSUE TITLE
Timeout Error Occurring during loginSelector Step in the Login Function

### ISSUE THREAD

**Issue by InvisibleExo** [lirantal/cypress-social-logins#63]
I would say this is more of issue on Puppeteer's Side, but wanted to reach out here first before further investigation and seeking help elsewhere. 
  I getting stuck at login function during the step for page.waitForSelector(options.loginSelector). It keeps getting a timeout error; even after I extended the Timeout by 3 times the default, or use a different selector for that function. Chromium does pop appear and  go to correct loginUrl. I'm currently stumped on what I'm missing or haven't considered when setting value for loginSelector Property. (I almost wonder if there should be an if Condition for that line, in case loginSelector is a link to public Url to login.)

Here what I have for Plugins.js:
`/* eslint-disable no-undef */
'use strict'

const puppeteer = require('puppeteer')

/**
 *
 * @param {options.username} string username
 * @param {options.password} string password
 * @param {options.loginUrl} string password
 * @param {options.args} array[string] string array which allows providing further arguments to puppeteer
 * @param {options.loginSelector} string a selector on the loginUrl page for the social provider button
 * @param {options.loginSelectorDelay} number delay a specific amount of time before clicking on the login button, defaults to 250ms. Pass a boolean false to avoid completely.
 * @param {options.postLoginSelector} string a selector on the app's post-login return page to assert that login is successful
 * @param {options.preLoginSelector} string a selector to find and click on before clicking on the login button (useful for accepting cookies)
 * @param {options.headless} boolean launch puppeteer in headless more or not
 * @param {options.logs} boolean whether to log cookies and other metadata to console
 * @param {options.getAllBrowserCookies} boolean whether to get all browser cookies instead of just for the loginUrl
 * @param {options.isPopup} boolean is your google auth displayed like a popup
 * @param {options.popupDelay} number delay a specific milliseconds before popup is shown. Pass a falsy (false, 0, null, undefined, '') to avoid completely
 * @param {options.cookieDelay} number delay a specific milliseconds before get a cookies. Pass a falsy (false, 0, null, undefined, '') to avoid completely.
 * @param {options.postLoginClick} string a selector to find and click on after clicking on the login button
 * @param {options.usernameField} string selector for the username field
 * @param {options.usernameSubmitBtn} string selector for the username button
 * @param {options.passwordField} string selector for the username field
 * @param {options.passwordSubmitBtn} string selector submit button
 * @param {options.additionalSteps} function any additional func which may be required for signin
 */

function delay(time) {
  return new Promise(function(resolve) {
    setTimeout(resolve, time)
  })
}

function validateOptions(options) {
  if (!options.username || !options.password) {
    throw new Error('Username or Password missing for social login')
  }
}

async function login({page, options} = {}) {
  if (options.preLoginSelector) {
    await page.waitForSelector(options.preLoginSelector)
    await page.click(options.preLoginSelector)
  }

  await page.waitForSelector(options.loginSelector, {timeout: 20000})

  if (options.loginSelectorDelay !== false) {
    await delay(options.loginSelectorDelay)
  }

  await page.click(options.loginSelector)
}

async function getCookies({page, options} = {}) {
  await page.waitForSelector(options.postLoginSelector)

  const cookies = options.getAllBrowserCookies
    ? await getCookiesForAllDomains(page)
    : await page.cookies(options.loginUrl)

  if (options.logs) {
    console.log(cookies)
  }

  return cookies
}

async function getLocalStorageData({page, options} = {}) {
  await page.waitForSelector(options.postLoginSelector)

  const localStorageData = await page.evaluate(() => {
    let json = {}
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i)
      json[key] = localStorage.getItem(key)
    }
    return json
  })
  if (options.logs) {
    console.log(localStorageData)
  }

  return localStorageData
}

async function getSessionStorageData({page, options} = {}) {
  await page.waitForSelector(options.postLoginSelector)

  const sessionStorageData = await page.evaluate(() => {
    let json = {}
    for (let i = 0; i < sessionStorage.length; i++) {
      const key = sessionStorage.key(i)
      json[key] = sessionStorage.getItem(key)
    }
    return json
  })
  if (options.logs) {
    console.log(sessionStorageData)
  }

  return sessionStorageData
}

async function getCookiesForAllDomains(page) {
  const cookies = await page._client.send('Network.getAllCookies', {})
  return cookies.cookies
}

async function finalizeSession({page, browser, options} = {}) {
  await browser.close()
}

async function waitForMultipleSelectors(selectors, options, page) {
  const navigationOutcome = await racePromises(
    selectors.map(selector => page.waitForSelector(selector, options))
  )
  return selectors[parseInt(navigationOutcome)]
}

async function racePromises(promises) {
  const wrappedPromises = []
  let resolved = false
  promises.map((promise, index) => {
    wrappedPromises.push(
      new Promise(resolve => {
        promise.then(
          () => {
            resolve(index)
          },
          error => {
            if (!resolved) {
              throw error
            }
          }
        )
      })
    )
  })
  return Promise.race(wrappedPromises).then(index => {
    resolved = true
    return index
  })
}

async function baseLoginConnect(typeUsername, typePassword, authorizeApp, postLogin, options) {
  validateOptions(options)

  const launchOptions = {headless: !!options.headless}

  if (options.args && options.args.length) {
    launchOptions.args = options.args
  }

  const browser = await puppeteer.launch(launchOptions)
  let page = await browser.newPage()
  let originalPageIndex = 1
  await page.setViewport({width: 1280, height: 800})
  await page.setExtraHTTPHeaders({
    'Accept-Language': 'en-USq=0.9,enq=0.8'
  })
  await page.setUserAgent(
    'Mozilla/5.0 (Windows NT 10.0 Win64 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36'
  )

  await page.goto(options.loginUrl)
  await login({page, options})

  // Switch to Popup Window
  if (options.isPopup) {
    if (options.popupDelay) {
      await delay(options.popupDelay)
    }
    const pages = await browser.pages()
    // remember original window index
    originalPageIndex = pages.indexOf(
      pages.find(p => page._target._targetId === p._target._targetId)
    )
    page = pages[pages.length - 1]
  }

  await typeUsername({page, options})
  await typePassword({page, options})

  if (options.additionalSteps) {
    await options.additionalSteps({page, options})
  }

  if (options.authorize) {
    await authorizeApp({page, options})
  }

  // Switch back to Original Window
  if (options.isPopup) {
    if (options.popupDelay) {
      await delay(options.popupDelay)
    }
    const pages = await browser.pages()
    page = pages[originalPageIndex]
  }

  if (options.postLoginClick) {
    await postLogin({page, options})
  }

  if (options.cookieDelay) {
    await delay(options.cookieDelay)
  }

  const cookies = await getCookies({page, options})
  const lsd = await getLocalStorageData({page, options})
  const ssd = await getSessionStorageData({page, options})
  await finalizeSession({page, browser, options})

  return {
    cookies,
    lsd,
    ssd
  }
}

module.exports.baseLoginConnect = baseLoginConnect

module.exports.GoogleSocialLogin = async function GoogleSocialLogin(options = {}) {
  const typeUsername = async function({page, options} = {}) {
    await page.waitForSelector('input#identifierId[type="email"]')
    await page.type('input#identifierId[type="email"]', options.username)
    await page.click('#identifierNext')
  }

  const typePassword = async function({page, options} = {}) {
    let buttonSelectors = ['#signIn', '#passwordNext', '#submit']

    await page.waitForSelector('input[type="password"]', {visible: true})
    await page.type('input[type="password"]', options.password)

    const buttonSelector = await waitForMultipleSelectors(buttonSelectors, {visible: true}, page)
    await page.click(buttonSelector)
  }

  const postLogin = async function ({page, options} = {}) {
    await page.waitForSelector(options.postLoginClick)
    await page.click(options.postLoginClick)
  }

  return baseLoginConnect(typeUsername, typePassword, null, postLogin, options)
}

module.exports.GitHubSocialLogin = async function GitHubSocialLogin(options = {}) {
  const typeUsername = async function({page, options} = {}) {
    await page.waitForSelector('input#login_field')
    await page.type('input#login_field', options.username)
  }

  const typePassword = async function({page, options} = {}) {
    await page.waitForSelector('input#password', {visible: true})
    await page.type('input#password', options.password)
    await page.click('input[type="submit"]')
  }

  const authorizeApp = async function({page, options} = {}) {
    await page.waitForSelector('button#js-oauth-authorize-btn', {visible: true})
    await page.click('button#js-oauth-authorize-btn', options.password)
  }

  const postLogin = async function ({page, options} = {}) {
    await page.waitForSelector(options.postLoginClick)
    await page.click(options.postLoginClick)
  }

  return baseLoginConnect(typeUsername, typePassword, authorizeApp, postLogin, options)
}

module.exports.MicrosoftSocialLogin = async function MicrosoftSocialLogin(options = {}) {
  const typeUsername = async function({page, options} = {}) {
    await page.waitForSelector('input[type="email"]')
    await page.type('input[type="email"]', options.username)
    await page.click('input[type="submit"]')
  }

  const typePassword = async function({page, options} = {}) {
    await delay(5000)

    await page.waitForSelector('input[type="password"]', {visible: true})
    await page.type('input[type="password"]', options.password)
    await page.click('input[type="submit"]')
  }

  const authorizeApp = async function({page, options} = {}) {
    await page.waitForSelector('button#js-oauth-authorize-btn', {visible: true})
    await page.click('button#js-oauth-authorize-btn', options.password)
  }

  const postLogin = async function ({page, options} = {}) {
    await page.waitForSelector(options.postLoginClick)
    await page.click(options.postLoginClick)
  }

  return baseLoginConnect(typeUsername, typePassword, authorizeApp, postLogin, options)
}

module.exports.CustomizedLogin = async function CustomizedLogin(options = {}) {
  if (options.usernameField && options.passwordField) {
    const typeUsername = async function({page, options} = {}) {
      await page.waitForSelector(options.usernameField, {visible: true})
      await page.type(options.usernameField, options.username)
      if (options.usernameSubmitBtn) {
        await page.click(options.usernameSubmitBtn)
      }
    }
    const typePassword = async function({page, options} = {}) {
      await page.waitForSelector(options.passwordField, {visible: true})
      await page.type(options.passwordField, options.password)
      if (options.passwordSubmitBtn) {
        await page.click(options.passwordSubmitBtn)
      }
    }
    return baseLoginConnect(typeUsername, typePassword, null, null, options)
  } else {
    return new Error('Please review your option properties. Propeties usernameField and passwordField are required as type String.')
  }
}`

Cypress Plugins folder: 
`/// <reference types="cypress" />

const { CustomizedLogin } = require('../../src/Plugins')

// ***********************************************************
// This example plugins/index.js can be used to load plugins
//
// You can change the location of this file or turn off loading
// the plugins file with the 'pluginsFile' configuration option.
//
// You can read more here:
// https://on.cypress.io/plugins-guide
// ***********************************************************

// This function is called when a project is opened or re-opened (e.g. due to
// the project's config changing)

/**
 * @type {Cypress.PluginConfig}
 */

const {customizedLogin} = require('../../src/Plugins').CustomizedLogin

module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
  on('task', {
    customizedLogin: CustomizedLogin
  })
}
`

Cypress test file:
`describe('Test Login', () => {
  it('Login with custom function', () => {
    // sites with extra security:
    // keybank? Linkedin? RingCentral?
    const username = Cypress.env('steamUserName')
    const password = Cypress.env('steamUserNamePW')
    const loginUrl = Cypress.env('loginUrl')
    const loginSelector = Cypress.env('loginSelector')
    const socialLoginOptions = {
      username,
      password,
      loginUrl,
      // Add username/pw fields and buttons and addtional steps
      usernameField: '#input_username',
      passwordField: '#input_password',
      passwordSubmitBtn: '#login_btn_signin',
      additionalSteps: async function({page, options} = {}) {
        await page.waitForSelector('#language_pulldown')
        await page.click('#language_pulldown')
        await page.click('#language_pulldown')
      },
      isPopup: true,
      logs: true,
      headless: false,
      // Selector not working
      loginSelector: loginSelector
    }

    cy.log(socialLoginOptions)

    return cy.task('customizedLogin', socialLoginOptions, {timeout: 80000}).then(({cookies}) => {
      cy.clearCookies()
      console.log(cookies)
    })
  })
})`

StackTrace:
`    at <unknown> (http://localhost:51204/__cypress/runner/cypress_runner.js:159616:20)
From previous event:
    at Context.task (http://localhost:51204/__cypress/runner/cypress_runner.js:159598:16)
From Your Spec Code:
    at Context.eval (webpack:///cypress/integration/loginTestNode.spec.js:31:15)
From Node.js Internals:
    TimeoutError: waiting for selector "a.global_action_link[href="https://store.steampowered.com/login/?redir=%3Fsnr%3D1_60_4__global-header&redir_ssl=1&snr=1_4_4__global-header"]" failed: timeout 20000ms exceeded
      at new WaitTask (C:\Users\Rigat\Project_cypress-social-logins\node_modules\puppeteer\lib\DOMWorld.js:549:29)
      at DOMWorld._waitForSelectorOrXPath (C:\Users\Rigat\Project_cypress-social-logins\node_modules\puppeteer\lib\DOMWorld.js:478:23)
      at DOMWorld.waitForSelector (C:\Users\Rigat\Project_cypress-social-logins\node_modules\puppeteer\lib\DOMWorld.js:432:18)
      at Frame.waitForSelector (C:\Users\Rigat\Project_cypress-social-logins\node_modules\puppeteer\lib\FrameManager.js:627:48)
      at Frame.<anonymous> (C:\Users\Rigat\Project_cypress-social-logins\node_modules\puppeteer\lib\helper.js:112:24)
      at Page.waitForSelector (C:\Users\Rigat\Project_cypress-social-logins\node_modules\puppeteer\lib\Page.js:1122:30)
      at login (C:\Users\Rigat\Project_cypress-social-logins\src\Plugins.js:48:15)
      at baseLoginConnect (C:\Users\Rigat\Project_cypress-social-logins\src\Plugins.js:169:10)
    at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:6)`

**Comment by ghost** [comment]
Hey, I'm not associated with the library or anything, but I have been trying to implement it myself and have run into a similar problem. It looks like you are using Headless: false, and isPopup:true, so you might want to add a popupDelay to your socialLoginOptions. This helped the puppeteer instance find the fields in the popup for me when I had that issue. I discovered the solution reading through some of the comments located here: 

https://github.com/lirantal/cypress-social-logins/issues/4

Hope this works for you!

**Comment by InvisibleExo** [comment]
popupDelay was helpful for waiting for selectors. Figured out the problem was caused by my selector. If I remove the href attribute as part of the selector, chromium had no problem picking the selector. It looks like I'll have to do more research with what are valid selector formats when working with puppeteer.

**Comment by InvisibleExo** [comment]
Probably should mention this in case other users have trouble with selectors and Puppeteer. Puppeteer uses `document.querySelectors`  , so if you try to use selectors used in jQuery, you might face timeout errors because Puppeteer can't find that selector. 
You can use check these links to get examples of valid selectors: 
[document.querySelector()](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector)
[CSS Selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors)

**Comment by lirantal** [comment]
@InvisibleExo the README has a section about troubleshooting. do you want to add a Q & A about this with a pull request? I'll gladly merge and appreciate your effort to document this for other readers 🙏

**Comment by InvisibleExo** [comment]
@lirantal Sure, I'll include this info in the README file. I'll include it when I push it along with my additions for Plugin.js so they can be reviewed. I want to run more e2e scenarios to make sure I don't introduce any issues.

**Comment by lirantal** [comment]
Thanks! 🙏
