### ISSUE TITLE
Google Oauth timeout error

### ISSUE THREAD

**Issue by takka** [lirantal/cypress-social-logins#68]
Hello there! 
I already saw some similar issues, but mine is a bit different.

So my react app uses Google JS Client library to handle the OAuth 2.0 flow. And I don't use any custom cookies etc, google handles things for me (so to be honest I don't know where and which data window needs to have to be in a logged-in state). 
I want to test the application, but basically, I need to login first to access anything.  
And I decided to try this plugin. 

First of all, it throws the same timeout error(that email field is not found). I investigated a lot, and now I managed to have the login process running but only in _not_ headless mode. 
If headless mode is true, then test fails with the same time out error, and `popupDelay` doesn't help.

![image](https://user-images.githubusercontent.com/1446795/100750795-34be0200-33ef-11eb-9667-3279147b78ad.png)

Now another thing, since I don't have any custom cookies, and google handles things for me, I see that with this plugin I still cannot do much, because probably I need to have `localStorage` and `sessionsStorage` from 'accounts.google.com' domain. Is this something doable? (I am not very familiar neither with cypress nor with puppeteer) And currently, at least in not headless mode I see that 'localStorage' and `sessionsStorage` are empty objects after task is done ((

**Comment by lirantal** [comment]
Is it failing for you in CI, or in a local dev environment when running it in headless mode?
The reason it probably fails is because google is unable to authenticate the source is legitimate and spawns up phone number, 2fa, or captcha validation. Just a guess, but this is what I've seen happening before.

**Comment by takka** [comment]
yea, in local dev environment, 
So in dev environment, I should always run it not in headless mode then

**Comment by lirantal** [comment]
> So in dev environment, I should always run it not in headless mode then

It also depends where you run it from. If you run it, even non-headless in a CI that spawns up tests in different locations (which they do) from what your social account was created then this will cause social logins to detect is as potential hack/fraud attempt

**Comment by Rykuno** [comment]
I'm also encountering this exact same issue following the documentation from the readme with Google :/.

**Comment by simsonek** [comment]
I am getting this on local dev machine and on jenkins. With headles set to true or fals it does not change anything

**Comment by lirantal** [comment]
@simsonek if you set headless to false, same?

**Comment by simsonek** [comment]
@lirantal yep, not sure what can I check in addition

**Comment by lirantal** [comment]
The original issue is not happening in non-headless mode. It is difficult to say why that is happening for you. Did you setup the correct selector for the plugin to find the login button, etc?

**Comment by simsonek** [comment]
@lirantal  sory for that, double checked it and you are right, the issue occurs only with headless: true, on non headless I am getting error that my browsers is not secure like on #71  :(

**Comment by lirantal** [comment]
Yep, that's... everyone's problem :-)
I don't have a way around it, it's basically anti-fraud preventions from these social login providers like Google, GitHub, etc. Some will ask you for a 2FA and others will show a CAPTCHA.
