### ISSUE TITLE
Google will discontinue support for sign-ins to Google accounts from embedded browser frameworks

### ISSUE THREAD

**Issue by HajekOndrej** [lirantal/cypress-social-logins#71]
Hi, thanks for this great plugin. I would just like to make sure, that the plugin is not affected by discontinuing the support for sign-ins from embedded browser frameworks, that is planned for the new year by google.

Thanks.

O.

**Comment by lirantal** [comment]
Interesting. Can you provide a link?
Do you know how they detect and know this to prevent?

**Comment by HajekOndrej** [comment]
> Interesting. Can you provide a link?
> Do you know how they detect and know this to prevent?

Absolutely, here comes: [blog post](https://developers.googleblog.com/2020/08/guidance-for-our-effort-to-block-less-secure-browser-and-apps.html)

They provide a way to check if you are affected.

**Comment by chan-dev** [comment]
Any updates if this will be affected, I'm planning on using this login with Google oauth2

**Comment by lirantal** [comment]
I've no idea.

**Comment by shakira-ahmed** [comment]
<img width="776" alt="Screen Shot 2021-01-11 at 10 12 33 AM" src="https://user-images.githubusercontent.com/33100871/104199504-88ac0580-53f5-11eb-8fe8-bfbc236b9ae1.png">
Came across this screen when trying to run the plugin, is it related to the issue described?

**Comment by lucy1017-liu** [comment]
Any update about the issue?

**Comment by piotrczarnak** [comment]
This is still issue is it any update ?

**Comment by fractaleater** [comment]
Seems like Google login is not going to work anymore.. at all. Must use headless: false to get anything going, and then it finds the username field, but is denied by Google policy, so can't reach password page.

Unless you're waiting to see if Google changes their policy, or a miracle work-around appears, perhaps would be best to put a disclaimer in the README that Google is no longer supported. Specifically, mark Google in "Supported identity providers" as "not-working".

Doing so might save someone, like myself, the time and trouble of trying to get something to work that has been specifically designed not to work.

Thanks for your hard work on this plugin though. Not trying to say you and your work are not appreciated. Just saying that Google login with this plugin is now a troll's errand.

**Comment by lirantal** [comment]
I indeed haven't tested that in a while so perhaps some things have changed. Appreciate the input here.

**Comment by lindsaymacvean** [comment]
I ended up just writing my own cypress steps to login. Going to document on this stackoverflow here 
https://stackoverflow.com/questions/74396602/how-to-log-in-to-cognito-google-oauth-using-cypress/74396755#74396755

**Comment by lirantal** [comment]
New version of cypress-social-logins includes the latest Puppeteer.

Going to close this for being stale but if any issues remain or more context to be shared, please comment and will re-open.
