### ISSUE TITLE
endless loading (gmail)

### ISSUE THREAD

**Issue by PaulinePoirot** [lirantal/cypress-social-logins#72]
Hello !

Thank to your plugins, I managed to connect to my gmail account. But for an unknow reason, my test "stop" (timeout of cypress) because the loading of gmail never finish.

I don't know if you had a similar issue or some things that would approach it.

I can write my email adress, then my password without problem, but when i log in : 

![image](https://user-images.githubusercontent.com/22679930/102071616-097cdf00-3e01-11eb-8fd0-6cc0de6b00e9.png)

Btw if i click in the url of cypress, firefox open a new windows and here the loading is good and i can saw my email. But I need my test to do it since i need to check something in it.

So idk if you know where can be the problem ? (If you want something from my code, just say it i don't know what you might need)

Thank you

update : In fact, i think i didn’t used the plugins well. But now (if i’m right) i have a different problem.

I use as a loginUrl for the const socialLoginOptions, the url of gmail. But since i want my test to « start » in the windows of the gmail log in, i assume that i don’t need any loginSelector. But if i don’t have a loginSelector, the test doesn’t work. 

So to be honest i’m still a bit lost lol

**Comment by lirantal** [comment]
New version of cypress-social-logins includes the latest Puppeteer.

Going to close this for being stale but if any issues remain or more context to be shared, please comment and will re-open.
