### ISSUE TITLE
Missing cookie name in returned data

### ISSUE THREAD

**Issue by quy-tran-xeniatech** [lirantal/cypress-social-logins#74]
With my app, after the user signs in with Google, there are 3 cookies set: id, G_AUTHUSER_H, G_ENABLED_IDPS. But cookie name (id) is missing in return data. I tried to increase the param:  cookieDelay: 50000 but the issue still happens. Please help me check.

Thanks

**Comment by quy-tran-xeniatech** [comment]
> With my app, after the user signs in with Google, there are 3 cookies set: id, G_AUTHUSER_H, G_ENABLED_IDPS. But cookie name (id) is missing in return data. I tried to increase the param: cookieDelay: 50000 but the issue still happens. Please help me check.
> 
> Thanks

 #[](url)

**Comment by quy-tran-xeniatech** [comment]
> With my app, after the user signs in with Google, there are 3 cookies set: id, G_AUTHUSER_H, G_ENABLED_IDPS. But cookie name (id) is missing in return data. I tried to increase the param: cookieDelay: 50000 but the issue still happens. Please help me check.
> 
> Thanks

I found out the root cause: if the cookie with httpOnly: true, it will be missed in returned data.  Please help if you have any work around to overcome this issue. Thanks

**Comment by lirantal** [comment]
@quy-tran-xeniatech is it possible that it is for a different domain? if so, you may need to specify it / use this config option: `getAllBrowserCookies`

Related: https://github.com/puppeteer/puppeteer/issues/3728
