### ISSUE TITLE
next-auth.js Target closed

### ISSUE THREAD

**Issue by cbwheadon** [lirantal/cypress-social-logins#76]
Hi, I'm following the example given here: https://next-auth.js.org/tutorials/testing-with-cypress but I'm failing at this point:
`.task('GoogleSocialLogin', socialLoginOptions)`

<img width="868" alt="Screenshot 2021-01-13 at 15 46 31" src="https://user-images.githubusercontent.com/537793/104475027-880e9d00-55b6-11eb-9d5e-2b6b09b8fbff.png">

These are the options I have set:

<img width="432" alt="Screenshot 2021-01-13 at 15 50 09" src="https://user-images.githubusercontent.com/537793/104475457-08350280-55b7-11eb-9db9-155d3f9aa752.png">

I have no idea what to look at to start diagnosing the issue. Do you have any ideas?

**Comment by love1esskris** [comment]
@cbwheadon Hi, I'm able to resolve this error by downgrading puppeteer to 7.1.0, you could change the version in package.json and delete node_modules and do `npm install`

**Comment by lirantal** [comment]
New version of cypress-social-logins includes the latest Puppeteer.

Going to close this for being stale but if any issues remain or more context to be shared, please comment and will re-open.
