### ISSUE TITLE
Google Social Login yields 400: invalid_request (missing: response_type)

### ISSUE THREAD

**Issue by phlprcks** [lirantal/cypress-social-logins#78]
I followed the example for Google social log in at https://github.com/lirantal/cypress-social-logins 

Cypress manages to open the Google Login in a new Window.  However, a
```
Error 400: invalid_request
Required parameter is missing: response_type
```
appears, suggesting that the response type (e.g. "token") is missing in the request. That is a required parameter for the OAuth process. From this plugin's documentation it must not be given as a parameter to the task. 

The test is running in Chrome 87

Does anyone else experience similar issues and could help? It is much appreciated! Thanks in advance

**Comment by lirantal** [comment]
New version of cypress-social-logins includes the latest Puppeteer.

Going to close this for being stale but if any issues remain or more context to be shared, please comment and will re-open.
