### ISSUE TITLE
Github Social Login example

### ISSUE THREAD

**Issue by mohammad-quanit** [lirantal/cypress-social-logins#79]
Hi there, I am trying to implement Github social login but not sure what will be the loginSelector should I put in it. Also, there is not a single example I find on the internet regarding Github login tests. Please if anyone implements this in their tests, please let me know.
  
Thanks

**Comment by lgsf** [comment]
I am also looking up for it.
Were you able to get it to work?
If anyone has found a way to make it work, please share.

**Comment by evemontalvao** [comment]
I'm having some trouble with Github social login as well, the loginSelector is never found, even though it's on the page. I'm looking desperately for an example too

**Comment by PierrickG34** [comment]
Hi, an example that works for Github for me : 
```
describe('Login', () => {
     it("Success for GitHub provider", () => {
        const keycloakConf = Cypress.env("keycloak");
        const cookiesName = keycloakConf.cookiesName;
        const socialLoginOptions = {
            username: keycloakConf.githubEmail,
            password: keycloakConf.githubPassword,
            loginUrl: Cypress.config().baseUrl,
            loginSelector: keycloakConf.loginSelector,
            postLoginSelector: keycloakConf.postLoginSelector,
            getAllBrowserCookies: true,
        };

        return cy
            .task("GitHubSocialLogin", socialLoginOptions)
            .then(({cookies}: { cookies: Cookie[] }) => {
                cy.clearCookies();

                const filteredCookies = cookies.filter((cookie: Cookie) =>
                    cookiesName.includes(cookie.name)
                );
                filteredCookies.forEach((cookie: Cookie) => {
                    cy.setCookie(cookie.name, cookie.value, {
                        domain: cookie.domain,
                        expiry: cookie.expires,
                        httpOnly: cookie.httpOnly,
                        path: cookie.path,
                        secure: cookie.secure,
                    });
                });

                Cypress.Cookies.defaults({
                    preserve: cookiesName,
                });

                cy.visit("");
            });
    });
})
```

username -> email used when login to github
password -> password used when login to github
loginUrl -> url for the login page that includes the social network buttons
loginSelector -> selector for github link provider where we should click to connect
postLoginSelector -> selector on the post-login page that can be asserted upon to confirm a successful login
getAllBrowserCookies -> I needed this to get cookies, you can try without it if you want

I hope it's help !

**Comment by lirantal** [comment]
Thanks @PierrickG34 
Is that also working for you from within a CI or from your own local dev machine?

**Comment by PierrickG34** [comment]
@lirantal, for now, I only used it with `cypress open` & `cypress run` on local machine for development and it's seem to works fine.

**Comment by lirantal** [comment]
Indeed this works as expected locally. The issues are from CI due to multi-factor authentication and captcha mechanisms :-)

**Comment by lirantal** [comment]
Appreciate sharing the code for others to review, but I'll close the ticket.
