### ISSUE TITLE
cy.task('GoogleSocialLogin') failed with error "Converting circular structure to JSON"

### ISSUE THREAD

**Issue by lucy1017-liu** [lirantal/cypress-social-logins#81]
Thanks for great plugin. I'm working on Google Social Sign on recently. I did a local demo using the examples provided in Github, but I got following errors. Can anyone take a look?

![image](https://user-images.githubusercontent.com/71241226/106123985-8daeda00-6195-11eb-8cd4-ba96b546ff0a.png)

**Comment by lirantal** [comment]
There's no serialization that we're doing in the plugin, so I don't know where that is coming from. Perhaps try to debug it further? If you try a different one, does it work better?

**Comment by lucy1017-liu** [comment]
Thanks for your replying. After debugging, I am able to login Google successfully. 

However, I have another question here. After running cy.task('GoogleSocialLogin', socialLoginOptions) and login Google successfully. Cypress test ended. 

What should I do to keep the brower keeping on the page after Google login since we have other tests need to run?

**Comment by lirantal** [comment]
The Cy.task() should be something that your test suites begin with and then you run your tests. To login with Google, you need to save the cookies from the google login, and apply them to Cypress. See the README example for this.

Note, that this will probably not run well on CI because Google will block attempts from unrecognized locations.

**Comment by lucy1017-liu** [comment]
If I understand you correctly, the examples have apply the cookies from Google login to Cypress using  Cypress.Cookies.defaults({
          preserve: cookieName
        }).

Then we can run my own tests.

How to call Google Social Login without cy.task()?  Since our tests are written within .js file under /integration folder. I'm not familiar with cy.task() at all...

**Comment by lirantal** [comment]
See here on the README for example usage: https://github.com/lirantal/cypress-social-logins#using-the-social-login

And see here for a branch with a working example: https://github.com/lirantal/cypress-social-logins/tree/test/add-e2e/__tests__/__e2e__

**Comment by lucy1017-liu** [comment]
Thanks a ton for your reply and examples. I'm able to run my own tests after Google Login !
