### ISSUE TITLE
Optional social login selector

### ISSUE THREAD

**Issue by groov1kk** [lirantal/cypress-social-logins#82]
Sometimes, you'll get a social login page during redirection actions from specific links. In these cases you don't need to click any social provider buttons at all. But as loginSelector is not optional, in cases of redirections you have to fill it with any fake locators. 

So, I've made a fix which makes  socialLogin selector optional.

**Comment by lirantal** [comment]
New version of cypress-social-logins includes the latest Puppeteer.

Going to close this for being stale but if any issues remain or more context to be shared, please comment and will re-open.
