### ISSUE TITLE
passwordSubmitBtn is not working with customized login

### ISSUE THREAD

**Issue by ghost** [lirantal/cypress-social-logins#84]
so i have been trying to login with apple using customLogin but i have not been able to use the passwordSubmitBtn as apple login form has to be username then the password so as i have usernameSubmitBtn working and it passes on to the password then i cant seem to press the passwordSubmitBtn as both of the cases have same btn id where one works with username and does not with password is very wierd `'button[id*="sign-in"]'` is just skips looking for passwordBtn and moves toward looking for post login selector.   

My specs.js is as follows :

  ```
 export const options = {
  usernameField: null,
  passwordField: null,
  username: null,
  password: null,
  loginUrl: Cypress.env("loginUrl"),
  headless: false,
  logs: true,
  loginSelector: null,
  isPopup: true,
  popupDelay: 5000,
  loginSelectorDelay: 1000,
  usernameSubmitBtn: null,
  passwordSubmitBtn: null,
  postLoginSelector : 'button[id*="sign-in"]',
  postLoginClick : 'button[id*="sign-in"]',
  moreStep : 'pin'
};

describe("Login", () => {
  it("Custom Login", () => {        
    options.postLoginClick = PASSWORD_SELECTOR
    options.loginSelector = 'form[action*="apple"]'
    options.usernameField = EMAIL_SELECTOR
    options.passwordField = PASSWORD_SELECTOR
    options.passwordSubmitBtn = 'button[id*="sign-in"]'
    options.usernameSubmitBtn = 'button[id*="sign-in"]';

      
    const cookieName = Cypress.env("cookieName");
    return cy
      .task("customizedLogin",aoptions)
      .then(({ cookies }) => {
        cy.clearCookies();

        const cookie = cookies
          .filter(cookie => cookie.name === cookieName)
          .pop();
        if (cookie) {
          cy.setCookie(cookie.name, cookie.value, {
            domain: cookie.domain,
            expiry: cookie.expires,
            httpOnly: cookie.httpOnly,
            path: cookie.path,
            secure: cookie.secure
          });
          Cypress.Cookies.defaults({
            whitelist: cookieName
          });
        }
      });
  });
});

```

my index.js is as follows : 

```
const {GoogleSocialLogin,FacebookSocialLogin,CustomizedLogin} = require('cypress-social-logins').plugins

module.exports = (on, config) => {
    on('task', {
      GoogleSocialLogin: GoogleSocialLogin,
      FacebookSocialLogin: FacebookSocialLogin,
      customizedLogin : (options) => {
        return CustomizedLogin(options)
    },
     
  }
)
}
```

**Comment by ghost** [comment]
![Screen Shot 2021-02-18 at 13 22 57](https://user-images.githubusercontent.com/45117063/108321948-f1548200-71ec-11eb-8d40-f1ca29cc01d7.png)

**Comment by InvisibleExo** [comment]
The selectors used by puppeteer might not be supported.  Please take a look at this document. https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector

**Comment by ghost** [comment]
I guess not as it should be a valid selector as the same selector works for usernameSubmitBtn but i have worked around it using customized login but the passwordSubmitBtn does not seem to work as documented.

**Comment by InvisibleExo** [comment]
Is the sign in flow: enter email -> hit submit -> enter pw -> hit submit?
Or
Enter email + pw -> hit submit?

If it's the later, have the passwordSubmitBtn defined, but not the usernameSubmitBtn. Try that if you haven't already. The Btn prop are optional in order for CustomizedLogin to work with both sign in flows mentioned above.

**Comment by ghost** [comment]
it is enter email -> hit submit -> enter pw -> hit submit apparently apple has the same selector for both usernameSubmit and passwordSubmitbtn so the issue might be caused as it thinks it pressed it while clicking on the usernameSubmit btn so it does not error out or anything it just does not work so i set a delay so that it would work

**Comment by InvisibleExo** [comment]
Thats what I'm thinking with hitting the button. Might need to have additional check if button needs to wait for 1 second if it becomes clickable again.  Maybe use the additionalSteps prop and define your function inside the index under plugins.

**Comment by ghost** [comment]
yup closing this as i solved it via customized login like you suggested thanks for the reply :)
