### ISSUE TITLE
facebookSocialLogin doesnt enter the complete facebook username

### ISSUE THREAD

**Issue by kalebhushan** [lirantal/cypress-social-logins#90]
I am using cypress-social-logins to authenticate a facebook user to my website exporting the `FacebookSocialLogin` task from `plugins/index.ts`. However, the username gets cut short as you can see in the screenshot below. My test looks like below:

`it('Login through Facebook', () => {

      const username = Cypress.env('fbSocialLoginUsername');
      const password = Cypress.env('fbSocialLoginPassword');
      const loginUrl = Cypress.env('loginUrl');
      const cookieName = Cypress.env('cookieName');
      const socialLoginOptions = {
        username: username,
        password: password,
        loginUrl: loginUrl,
        headless: false,
        logs: false,
        loginSelector: 'a[href="/users/auth/facebook?origin=https%3A%2F%2Fwebapp.preprod.applyboard.dev%2F%3F"]',
        postLoginClick: "facebook.button",
        postLoginSelector: ".account"
      };`

<img width="1440" alt="Facebook_incompleteString" src="https://user-images.githubusercontent.com/36714200/110686826-dbaff800-81ad-11eb-9a29-3d30dff134a3.png">

**Comment by kalebhushan** [comment]
Has anyone seen this before? Happens with facebook but not with google.

**Comment by XeniyaShirinova** [comment]
Did you tried to interact with Facebook form without using cypress-sosial-login library? 
I've found this `cy.get(...).invoke('val', 'email@example.com')` as a work around which can help. https://github.com/cypress-io/cypress/issues/5480

**Comment by kalebhushan** [comment]
> Did you tried to interact with Facebook form without using cypress-sosial-login library?
> I've found this `cy.get(...).invoke('val', 'email@example.com')` as a work around which can help. [cypress-io/cypress#5480](https://github.com/cypress-io/cypress/issues/5480)

We can use cy.get but that would mean not using the recommended plugin. While it will work, it wouldnt be optimal.

**Comment by s-kris** [comment]
I can confirm that the same issue is happening to me 19 out of 20 times when trying to login with facebook.

For some reason, the email is correctly typed only 1 time. Totally random!

cypress: 9.1.1
cypress-social-login: 1.13.0

**Comment by lirantal** [comment]
Going to close this for being stale but if any issues remain or more context to be shared, please comment and will re-open.
