### ISSUE TITLE
AdditionalSteps fails for entering google 2fa code

### ISSUE THREAD

**Issue by BhushanAB** [lirantal/cypress-social-logins#91]
I am using the additionalSteps option to enter a token in google 2fa authentication. The token is generated using the totp-generator plugin. The additional steps looks like:

`additionalSteps: async function moreSteps() => {cy.get('input#idvPin').type(token);}`

However, `GoogleSocialLogin` fails because it does not acknowledge the 2fa code field and fails trying to look for my `postLoginSelector`. This means `additionalSteps` is not triggered before `postLoginSelector`.  The error and screenshot are below. From the screenshot it is clear that the app page was never reached and the token was never entered on google 2fa input field. Still the error isnt about `additionalSteps` but `postLoginSelector`

`CypressError
cy.task('GoogleSocialLogin') failed with the following error:
waiting for selector <postLoginSelector> failed: timeout 30000ms exceeded`

<img width="1409" alt="Screen Shot 2021-03-16 at 10 40 37 AM" src="https://user-images.githubusercontent.com/79859144/111329094-3bdaea00-8645-11eb-82dc-94504a82bad2.png">

**Comment by InvisibleExo** [comment]
Where did you define your additionalsteps property? Have you read the troubleshoot section regarding additionalsteps?

**Comment by BhushanAB** [comment]
> Where did you define your additionalsteps property? Have you read the troubleshoot section regarding additionalsteps?

Under the `const socialLoginOptions`

**Comment by InvisibleExo** [comment]
Which file? In your plugins or test file? Looking at your code snippet, it looks like you defined it in your test file. You need to define that property in plugin file.

**Comment by BhushanAB** [comment]
> Which file? In your plugins or test file? Looking at your code snippet, it looks like you defined it in your test file. You need to define that property in plugin file.

Got it thanks. I was indeed defining it in the test file. Read the troubleshooting steps later. Do you have an example of how can this be defined for GoogleSocialLogin?

**Comment by InvisibleExo** [comment]
The troubleshooting q and a provide in the example near the bottom of the Readme file.

**Comment by BhushanAB** [comment]
> The troubleshooting q and a provide in the example near the bottom of the Readme file.

Thanks a lot.
