### ISSUE TITLE
Cannot Complete Google Oath Sign-on Using Cypress-social-login

### ISSUE THREAD

**Issue by sarathchandrakvn** [lirantal/cypress-social-logins#92]
Hello Team,

I'm unable to login into my client that uses Google Oauth as a sign-on. Below are steps :

1. When the automation job kicks off, it initially navigates to google accounts sign-on.
2. Using cypress-social-login, it can login fine into the google account.
3. After google login, it goes to my client page that has a button for log-in (Assuming it had already logged in from previous window) it should now let the login pass.
4. Instead I see error as attached in screenshot below.

<img width="1531" alt="Error" src="https://user-images.githubusercontent.com/18638411/111585561-bbb7a000-877c-11eb-992d-cf91d87e46d7.png">

Platform : MacOS Catalina (10.15.7)
Browser : Electron 87.
Cypess : 6.6.0 / 6.7.0 / 6.7.1

This issue is intermittent but of the times It occurs about 6 or 7 out of 10, causing our builds to fail. Any help on where to look at, how to debug, Greatly appreciate.

**Comment by lirantal** [comment]
Going to close this for being stale but if any issues remain or more context to be shared, please comment and will re-open.
