### ISSUE TITLE
Running in headless mode == true  in google login will  return google login with captcha 

### ISSUE THREAD

**Issue by osky9913** [lirantal/cypress-social-logins#94]
When I used in config headless = true then this will occur
![Untitled](https://user-images.githubusercontent.com/36959325/114705552-2500e380-9d28-11eb-8508-a32e3e0e56f6.png)
)

if I am not in headless mode everything works fine

**Comment by lirantal** [comment]
Going to close this for being stale but if any issues remain or more context to be shared, please comment and will re-open.
