### ISSUE TITLE
Error: net::ERR_CERT_AUTHORITY_INVALID at https://localhost:8080/#/

### ISSUE THREAD

**Issue by marcoarruda** [lirantal/cypress-social-logins#95]
Hi

I have this vue.js app which, after some hacks (creating local certificate and enabling my dev env for social auth), I could make it testable in my local environment using `https://localhost:8080/`.

Althought cypress chrome browser does not enter the page due to the invalid authority of my self-signed certificate.
I didn't find any issues related to that. Maybe I am missing something in my way to the tests?

`Error: net::ERR_CERT_AUTHORITY_INVALID at https://localhost:8080/#/`

Thanks in advance

**Comment by lirantal** [comment]
Going to close this for being stale but if any issues remain or more context to be shared, please comment and will re-open.
