### ISSUE TITLE
How i can close the "Facebook cookie" window?

### ISSUE THREAD

**Issue by Artem-Kuznetsov-rms** [lirantal/cypress-social-logins#98]
How i can close the "Facebook cookie" window

![image](https://user-images.githubusercontent.com/80107439/118951408-bdac0400-b963-11eb-9c5e-c0b45e96dc2a.png)

I used method and link, but in my case this don't work.

link - [https://github.com/lirantal/cypress-social-logins](url)

This is my code:

```
describe('5 Login account Faceboock', function()
{  
    it('Faceboock', function()
    {   
        const username= Cypress.env('Faceboock-username')
        const password= Cypress.env('Faceboock-password')      
        const cookieName= Cypress.env('Cookie_Facebook')
        const socialLoginOptions = {
            username,
            password,
            loginUrl: `${Cypress.env('Url')}/sign-in`,
            loginSelectorDelay: 5000,
            headless: false,
            logs: true,
            loginSelector: ('[id="facebookLoginButton"]'),
            isPopup: true,
            popupDelay: 5000,
            postLoginSelector: 'a[href="/investment-properties"]'
        }       
        return cy.task('FacebookSocialLogin', socialLoginOptions)
            .then(({cookies}) => {
            cy.clearCookies()                
            const cookie = cookies
                .filter(cookie => cookie.name === cookieName).pop()
            if (cookie) {
                cy.setCookie(cookie.name, cookie.value, {
                    domain: cookie.domain,
                    expiry: cookie.expires,
                    httpOnly: cookie.httpOnly,
                    path: cookie.path,
                    secure: cookie.secure
                })          
                Cypress.Cookies.defaults({
                    preserve: cookieName
                })
            }
            cy.visit(`${Cypress.env('Url')}`)  
            cy.clearCookies()
            Cypress.Cookies.defaults({
                preserve: cookieName
            })           
        }) 
    })    
})
```

**Comment by itsjenke** [comment]
+1 Are there any solutions to the problem? Maybe wait and click for _button[data-cookiebanner="accept_button"]_ ?

**Comment by alucardu** [comment]
Also having this issue (Netherlands)

![image](https://user-images.githubusercontent.com/779921/124600929-1c4a1600-de1c-11eb-8666-3b13e3db9e0d.png)

**Comment by lirantal** [comment]
Hi there

Looks like you missed up on the disclaimer in the README: 
![image](https://user-images.githubusercontent.com/316371/124496630-58508d00-ddc2-11eb-9e2c-532ceba27194.png)

**Comment by lirantal** [comment]
I'll close, if you don't mind.

**Comment by Gogowitsch** [comment]
@SimenB @xiphirx @gaearon @bvaughn @kayhadrin Do you happen to know a good way to test or mock a Facebook login on my own website? 

I don't want my test suite to cover Facebook code, nor do I care to test the credentials of a particular test user. 

I just want to know if my integration is healthy in a continuous integration pipeline.
