### ISSUE TITLE
Getting This browser or app may not be secure error after entering the email address for google login

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [lirantal/cypress-social-logins#99]
I am using cypress social login plugin to sign in to my web application via google. During the automation test I can see automated bot typing the google username(email). After typing the username I am getting directed to the below page and not getting the UI to enter the password.

![Screenshot from 2021-05-24 01-26-05](https://user-images.githubusercontent.com/31848014/119274840-8ffadf80-bc2f-11eb-85ba-9d313d5efdb7.png)

`cy.task('GoogleSocialLogin') failed with the following error:

> waiting for selector "input[type="password"]" failed: timeout 30000ms exceeded`

Browser URL of the landing error page is 
`https://accounts.google.com/signin/v2/deniedsigninrejected?continue=https%3A%2F%2Faccounts.google.com%2Fsignin%2Foauth%2Flegacy%2Fconsent%3Fauthuser%3Dunknown%26part%3DAJi8hANmW3bxhklUTWBt7aUhxOAXMxEbSlI2g94_lhHxwO3yL6iDQBa7VUCAhapFofLvzpZ-oj81FyeXCg6VLKCl4SrdOk0J44--eQHfksANOudUTs7_2Lw-nEU9xXSes5xTwVJlWF5XBAgYnZHegeDOm_JhZ7d6Mvec5b7w1hRRdcdu3ln60ECqbZbNJtMZ-x7AGu9Yqq64TEvuTW-eNlFkxULTG0PvJwoT7Eqi8BN-9Idlh9TwzIEgh8pks5HQbPHWZ27SQfGWMXHIZa0_nqo8dak1ghTCXAz2HrD-1knOSY281O5h7ulm6PU50RfYSsIk-h4nNzdhI-k-XsENf8twbZCLRispimLgG6YefHWEBtQm8VmKm_BvSnlk9M6zH3-2BR2oT-3xNoT3GX1X8_GhUQaw0lkZ_KS2kARuzKhFcRlHWSbv4GeNCz_P8t-ZnNiNgQ6fSVUU3ip3coOEFAYy6DvSCQhCzhz9QgY1MJy3WBDfbHnOE6Euj95MaV6snR_a3U0Eoy0ssSTkowlvy02E1uSOmeEirMO2f4ZZKgnq421pXMmbuvwb-mMudbkfp2WtCbBWLYLs8aJl2jUrz-oEyjSDi7oK3k7xQqYRpWNdeWKE4k12i0g%26as%3DS-1895258642%253A1621799681112165%26client_id%3D717762328687-iludtf96g1hinl76e4lc1b9a82g457nn.apps.googleusercontent.com%23&sacu=1&oauth=1&rip=1&flowName=GlifWebSignIn&flowEntry=ServiceLogin`

**Note**
I have allowed the less secure apps for the related google account

**Comment by baptisteArno** [comment]
Same issue! Did you find a solution?

(The login flow works fine when testing on my nonautomated browser)

**Comment by baptisteArno** [comment]
Duplicate #43

**Comment by Jailani134** [comment]
Any Solution for above issue?

**Comment by lirantal** [comment]
Going to close this for being stale but if any issues remain or more context to be shared, please comment and will re-open.
